### ISSUE TITLE
Unable to re-join a meeting in Safari, MacOS

### ISSUE THREAD

**Issue by abhijeet-toptal** [aws/amazon-chime-sdk-js#1097]
**Timeline**
Outline the main actions the user performed and when:

* User joins the meeting
* User leaves the meeting
* Important: Unlike demo app, we don't redirect user to the join page again, and user can choose to join back the same room from the same screen.
* User tries to join the meeting again, this time we don't ask user to select devices again.
* User is unable to join the meeting.

**Describe the bug**
The issue is only with Safari, MacOS, it works fine in Safari, iOS and all other browsers on Mac and Windows.
Have attached the entire log file, but here are the highlights:

```[Info] 2021-02-24T15:19:07.504Z [INFO] SDK - no audio device chosen, creating empty audio device (chime.js, line 16)
[Info] 2021-02-24T15:19:07.505Z [INFO] SDK - requesting new audio device with constraint null (chime.js, line 16)
[Info] 2021-02-24T15:19:07.509Z [INFO] SDK - got audio device for constraints null (chime.js, line 16)
[Info] 2021-02-24T15:19:07.510Z [INFO] SDK - no audio-video controller is bound to the device controller (chime.js, line 16)
[Info] 2021-02-24T15:19:07.511Z [INFO] SDK - stopping audio track (chime.js, line 16)
[Info] 2021-02-24T15:19:07.513Z [INFO] SDK - API/DefaultDeviceController/stopVideoPreviewForVideoInput "video-local" (chime.js, line 16)
[Info] 2021-02-24T15:19:07.513Z [INFO] SDK - API/DefaultAudioVideoFacade/77f74507-bf55-49c5-af1b-97d4ee03d365/89dff643-4217-d0c8-8673-cc7bf3e9545a/stopVideoPreviewForVideoInput "video-local" (chime.js, line 16)
[Warning] 2021-02-24T15:19:07.514Z [WARN] SDK - no transition found from NotConnected with Disconnect (chime.js, line 16)
[Info] 2021-02-24T15:19:07.515Z [INFO] SDK - API/DefaultAudioVideoFacade/77f74507-bf55-49c5-af1b-97d4ee03d365/89dff643-4217-d0c8-8673-cc7bf3e9545a/stop (chime.js, line 16)
[Info] 2021-02-24T15:19:07.543Z [INFO] SDK - no audio device chosen, creating empty audio device (chime.js, line 16)
[Info] 2021-02-24T15:19:07.543Z [INFO] SDK - requesting new audio device with constraint null (chime.js, line 16)
[Info] 2021-02-24T15:19:07.546Z [INFO] SDK - got audio device for constraints null (chime.js, line 16)
[Info] 2021-02-24T15:19:07.546Z [INFO] SDK - no audio-video controller is bound to the device controller (chime.js, line 16)
[Info] 2021-02-24T15:19:07.547Z [INFO] SDK - stopping audio track (chime.js, line 16)
[Info] 2021-02-24T15:19:07.548Z [INFO] SDK - API/DefaultDeviceController/stopVideoPreviewForVideoInput "video-local" (chime.js, line 16)
[Info] 2021-02-24T15:19:07.548Z [INFO] SDK - API/DefaultAudioVideoFacade/77f74507-bf55-49c5-af1b-97d4ee03d365/89dff643-4217-d0c8-8673-cc7bf3e9545a/stopVideoPreviewForVideoInput "video-local" (chime.js, line 16)
[Warning] 2021-02-24T15:19:07.549Z [WARN] SDK - no transition found from NotConnected with Disconnect (chime.js, line 16)
[Info] 2021-02-24T15:19:07.549Z [INFO] SDK - API/DefaultAudioVideoFacade/77f74507-bf55-49c5-af1b-97d4ee03d365/89dff643-4217-d0c8-8673-cc7bf3e9545a/stop (chime.js, line 16)
[Info] 2021-02-24T15:19:07.847Z [INFO] SDK - DefaultDeviceController video dimension 960 x 540 (chime.js, line 16)
[Info] 2021-02-24T15:19:07.848Z [INFO] SDK - Supported Constraints in this browser {"aspectRatio":true,"deviceId":true,"echoCancellation":true,"facingMode":true,"frameRate":true,"groupId":false,"height":true,"sampleRate":false,"sampleSize":false,"volume":true,"width":true} (chime.js, line 16)
[Info] 2021-02-24T15:19:07.849Z [INFO] SDK - browser is safari 13 (13.1.3) (chime.js, line 16)
[Info] 2021-02-24T15:19:07.849Z [INFO] SDK - WebRTC unified plan is required for safari (chime.js, line 16)
[Info] 2021-02-24T15:19:07.856Z [INFO] SDK - adding meeting observer (chime.js, line 16)
[Info] 2021-02-24T15:19:07.857Z [INFO] SDK - adding device change observer (chime.js, line 16)
[Info] 2021-02-24T15:19:07.857Z [INFO] SDK - API/DefaultDeviceController/addDeviceChangeObserver (chime.js, line 16)
[Info] 2021-02-24T15:19:07.857Z [INFO] SDK - API/DefaultAudioVideoFacade/77f74507-bf55-49c5-af1b-97d4ee03d365/a41885ba-be22-2330-3066-218c7d72a318/addDeviceChangeObserver (chime.js, line 16)
[Info] 2021-02-24T15:19:07.859Z [INFO] SDK - API/DefaultAudioVideoFacade/77f74507-bf55-49c5-af1b-97d4ee03d365/a41885ba-be22-2330-3066-218c7d72a318/realtimeSubscribeToAttendeeIdPresence (chime.js, line 16)
[Info] 2021-02-24T15:19:07.860Z [INFO] SDK - API/DefaultAudioVideoFacade/77f74507-bf55-49c5-af1b-97d4ee03d365/a41885ba-be22-2330-3066-218c7d72a318/subscribeToActiveSpeakerDetector (chime.js, line 16)
[Info] 2021-02-24T15:19:07.861Z [INFO] SDK - adding meeting observer (chime.js, line 16)
[Info] 2021-02-24T15:19:07.862Z [INFO] SDK - API/DefaultAudioVideoFacade/77f74507-bf55-49c5-af1b-97d4ee03d365/a41885ba-be22-2330-3066-218c7d72a318/addObserver (chime.js, line 16)
[Info] 2021-02-24T15:19:07.862Z [INFO] SDK - API/DefaultAudioVideoFacade/77f74507-bf55-49c5-af1b-97d4ee03d365/a41885ba-be22-2330-3066-218c7d72a318/addContentShareObserver (chime.js, line 16)```

**Platform**
 - OS: MacOS
 - Browser: Safari
 - Browser Version: 13, 14 
 - Amazon Chime SDK GitHub Commit: Latest(2.5.0)

**Comment by abhijeet-toptal** [comment]
[RocketJudge - Desktop Safari - Console Logs - Bug - Cannot rejoin room.txt](https://github.com/aws/amazon-chime-sdk-js/files/6043447/RocketJudge.-.Desktop.Safari.-.Console.Logs.-.Bug.-.Cannot.rejoin.room.txt)

**Comment by abhijeet-toptal** [comment]
@vidya-mohan @ajselvar @ajselvar-work @nicklera1 @RidipDe

**Comment by michhyun1** [comment]
Hey @abhijeet-toptal, what is the error that you are seeing?

I deployed a version of the SDK demo/browser demo, and I tried to reproduce this by following these steps:

1. User joins a meeting "123"
2. User leaves the meeting
3. User is navigated to the join meeting form again, and joins again using the same meeting id: "123"
4. Verify that the user can rejoin the meeting

This is also unlikely, but could you double check that the meeting is not being ended based on one of these criteria: https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html (scroll to the bottom)

**Comment by abhijeet-toptal** [comment]
@michhyun1 I think you missed an important note in the issue, you don't have to do step 3, "User is navigated to the join meeting form again", because you are creating a new app context. Please try joining the same meeting without refreshing the screen.

**Comment by abhijeet-toptal** [comment]
@michhyun1 any updates?

**Comment by michhyun1** [comment]
@abhijeet-toptal I just tried reproducing this again, this time without leaving the meeting page after I left the meeting. The steps I took were:

1. Comment out [this line](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2245) of the js sdk demo app.
2. Run the demo
3. Join the meeting 'test' on a Chrome tab as 'Michael Chrome'
4. . Join the meeting 'test' as 'Michael' on Safari MacOS. Verify that 'Michael Chrome' can see 'Michael'
5. As 'Michael', leave the meeting. I am no longer redirected to the meeting join form, instead I am still on the meeting UI. Verify that I am no longer showing on 'Michael Chrome' meeting page.
6.  On 'Michael' -  Call app.audioVideo.start() from the developer tools console.
7. Without being prompted by getUserMedia again, verify that I can enable my local video by pressing the video icon.

If you are having issues, I think your logs might have been cut a bit short. Could you try uploading a complete logs so that we can see what the error is that you are seeing? Thanks.

**Comment by abhijeet-toptal** [comment]
Couldn't reproduce this in latest safari.
