### ISSUE TITLE
Chime real time transcription failing

### ISSUE THREAD

**Issue by Aeramor** [aws/amazon-chime-sdk-js#2232]
### What happened and what did you expect to happen?

Normally we see all users of a meeting showing up in our captioning. This morning it would randomly only transcribe a few people and randomly switch to a new set of people every few minutes without us doing anything (including muting/unmuting). As we continued testing we started randomly seeing transcription events from an hour before come in, so I'm guessing there is something broken on the Chime/Transcribe server end.
We spent over an hour testing this, multiple versions/clients etc. we have been testing extensively the past few days and no changes on our end before hitting this issue.

To ensure it wasn't a fluke, we made a new session, fully refreshed everything, rebooted servers, updated from 2.27 -> 2.30.1 JS and still same issue persisted. We even watched the messages direct from chime and saw they were not coming through so not an issue on the front end.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Start a chime session with transcribe enabled, join with more than 4 participants and watch caption results.

### Amazon Chime SDK for JavaScript version

2.27 - 2.30.1 (tested both)

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 101.0.4951.54 (Official Build) (64-bit)

### Meeting and Attendee ID Information.

"MeetingId":"3e2b5d4f-3f5a-46d5-84e0-a468d28f0706"
"AttendeeId":"ca57741e-93c6-7f7a-eead-ebe1e6eba808"

### Browser console logs

[session.log](https://github.com/aws/amazon-chime-sdk-js/files/8691393/session.log)

**Comment by Aeramor** [comment]
It does, we even see it happening in Slack captions so we know it's not our platform.
To be clear it's mostly just large delays (minutes usually sometimes hours!), sometimes we never see the caption for certain speakers but could just be they are even more delayed.
This is a critical service for us, we use the realtime captioning for accessibility of our application.

**Comment by Aeramor** [comment]
@noahmako thanks for looking into it, had tested this morning and issues persisted, after writing the above comment I got status update from the team and they're now seeing the transcriptions working as expected. We'll continue testing and I'll update here.

**Comment by noahmako** [comment]
Thanks for the additional context. We are able to repro the issue in our side in some cases and are actively investigating. We will follow up with updates here as we have them.

**Comment by Aeramor** [comment]
It looked like it was fixed for awhile but it has started happening again @noahmako.

**Comment by noahmako** [comment]
Hi @Aeramor, the issue was pinpointed down last week to a change made in the Transcribe service. The Transcribe team is rolling things back to get to a stable state, I have asked them to provide an ETA. There was a rollback before which was quickly reverted, which is most likely why you saw it fixed temporarily. The first regions are being deployed to again today, and we will confirm if this fixes the issue.

**Comment by noahmako** [comment]
Hi all, the attempted rollbacks in the Transcribe service did not appear to fix the issue. The Transcribe team is actively investigating with high severity. We do not have a firm ETA at the moment, but will provide any updates here.

**Comment by Aeramor** [comment]
We're still seeing this issue occur somewhat frequently. Today delays were over an hour and sometimes we saw the wrong attendee attributed to the caption. Any update?

**Comment by noahmako** [comment]
Hi @Aeramor,

We appreciate your patience as we worked through this issue. The root cause was a regression in Transcribe's streaming backend which led to unstable & high latencies. This took a while for the team to track down and root cause. The fix has now been deployed to all commercial regions. Please let us know if you are still seeing long delays in receiving transcripts.

Best,
Noah

**Comment by Aeramor** [comment]
Thanks @noahmako, that's great news. We'll keep an eye out for issues and report back if we find any.

**Comment by noahmako** [comment]
Hi @Aeramor, I wanted to follow up to see if you are still facing any issues with the live transcription feature. I am closing this issue as the issue appears to be resolved from our end. Please re-open the issue if you feel this is not appropriate.

Thanks again for your patience as we worked towards a resolution.

Best,
Noah

**Comment by noahmako** [comment]
Hi @Aeramor, we are investigating. If this happens again, can you share the meeting ID? This will help us dig into the issue further.

**Comment by Aeramor** [comment]
Will do, we saw it in 2 meetings back to back (over 8 hours) but haven't seen again since. Will continue monitoring.

**Comment by richhx** [comment]
Hi @Aeramor, wanted to follow-up with you to see if you had any issues with this?
