### ISSUE TITLE
For remote attendees - Video/ Screen Stream frozen for disconnected attendee during call

### ISSUE THREAD

**Issue by ankit-maheshwari** [aws/amazon-chime-sdk-js#561]
**Describe the bug**
If an attendee is disconnected from the internet during the call, while his/her video and screen share stream is enabled. It shows frozen video streams for both video & screen share on the remote attendee's screens.  The video tiles of the disconnected attendee don't update for the remote attendees and remain on the screen.

**Platform**
 - OS: Windows, MacOS
 - Browser: Chrome/ Firefox
 - Browser Version: Latest
 - Amazon Chime SDK GitHub Commit: 1.7.0

**Comment by simmkyu** [comment]
Thanks for reporting.

Repro steps in the Chime SDK demo
1. UserA opens the SDK demo in the iOS Safari and joins a meeting.
2. UserB opens the SDK demo in the desktop Chrome and joins the same meeting.
3. UserA and UserB enable local videos.
4. UserB turn Wi-Fi off in the computer.
5. In the UserA's demo, UserB's video immediately freezes. But UserB still exists in the roster.
6. After several seconds, UserB disappears from the roster in the UserA's demo. the frozen UserB video still exists.

**Comment by dmtux** [comment]
Hello Dear AWS Team,

Any updates regarding this issue?

Thanks,
Denis

**Comment by efortney** [comment]
Hi AWS team, we are seeing this problem as well. I have been able to reproduce by using Network Link Conditioner.

**Comment by tarunkolla** [comment]
Any update on this? We are having similar issues with screen share and I could reproduce this on the demo app although it wasn't consistent

**Comment by edwardbc** [comment]
Still happening on +2.0.0 , mostly on two user sessions. I wasn't able to replicate it on more three users or more. 

Another problem I noticed with this bug, is that if in some cases when UserB comes back, UserA is not able to see him due the conflict created by the frozen video tile, even if it already dissapeared.

**Comment by rachinkapoor** [comment]
Do we have ETA for the fix?
Is there any workaround? 
Eg. Can we listen to any events or watch matrix to detect the frozen screen and take some steps to fix it?

**Comment by p-foucht** [comment]
Some users have been referencing this thread in regards to black tiles, so just to clarify -- there are two issues here

1. The frozen videos caused by network reconnection. We are in the process of investigating this and will provide updates here

2. Black videos, particularly when changing your a video grid layout from standard to an active speaker layout. This is likely caused improperly binding/unbinding the video tile. For users having these issues, I would recommend relying on using pure CSS to adjust the layout of your video grid, as opposed to removing/adding in new video elements in different spots of the DOM. Depending on the implementation and the framework, there could be race conditions where the unbinding happens after the binding occurs. You can refer to this [VideoGrid](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/components/ui/VideoGrid/index.tsx) in the component lib as an example CSS implementation

**Comment by rachinkapoor** [comment]
@p-foucht 
Yes, I understand we have two issues. 
The frozen video issue has become a critical issue for us as it is directly impacting our business.
ETA/some visibility/workarounds will be very helpful.

We are also concerned about the second issue, but, that's for an upcoming feature. Thanks for the advice on the second issue.

**Comment by hensmi-amazon** [comment]
Note https://github.com/aws/amazon-chime-sdk-js/pull/1073 fixes the additional issue in https://github.com/aws/amazon-chime-sdk-js/issues/561#issuecomment-737302066 .  The frozen video before reconnection has to do with not timing out the connection properly on the backend (and therefore will require backend deployment)

**Comment by hensmi-amazon** [comment]
The backend fix has started deployment and will take around a week to deploy to all regions.  I will close this ticket once both the backend change has been deployed and verified, and we have released a SDK version with the above fix.

**Comment by ellismarte** [comment]
we're still seeing frozen videos -- is there anything that the frontend needs to do?

**Comment by hensmi-amazon** [comment]
Hi @ellismarte , are these frozen videos related to disconnected attendees, as covered in description?  Otherwise it may be a different issue.

**Comment by ellismarte** [comment]
@hensmi-amazon we've seen it where a user is on a call & while they are talking the video freezes and never resumes

**Comment by hensmi-amazon** [comment]
Can you cut a new issue and provide logs?  I am going to close this current issue because it covers a specific problem (frames staying frozen after disconnection and never going away), other frozen frames may be for a different problems and It can be confusing if they are all using the same issue. The fixes mentioned in https://github.com/aws/amazon-chime-sdk-js/issues/561#issuecomment-780754914 and https://github.com/aws/amazon-chime-sdk-js/issues/561#issuecomment-782522018 have been released/deployed.
